set (proj Anima-Public)

set (cmake_args
  -DCMAKE_C_FLAGS:STRING=${cmake_flags}
  -DCMAKE_CXX_FLAGS:STRING=${cmake_flags}
  -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DEXECUTABLE_OUTPUT_PATH=${CMAKE_BINARY_DIR}/bin
  -DLIBRARY_OUTPUT_PATH=${CMAKE_BINARY_DIR}/lib
  -DBUILD_TOOLS:BOOL=ON
  -DBUILD_TESTING:BOOL=OFF
  -DBUILD_ALL_MODULES:BOOL=ON
  -DBUILD_MODULE_MATHS:BOOL=ON
  -DBUILD_MODULE_FILTERING:BOOL=ON
  -DBUILD_MODULE_REGISTRATION:BOOL=ON
  -DBUILD_MODULE_DIFFUSION:BOOL=ON
  -DBUILD_MODULE_SEGMENTATION:BOOL=ON
  -DBUILD_MODULE_QUANTITATIVE_MRI:BOOL=ON
  -DTinyXML2_INCLUDE_DIR:PATH=${TinyXML2_SRC_DIR}
  -DTinyXML2_LIBRARY_DIR:PATH=${TinyXML2_BUILD_DIR}
  -DUSE_NLOPT=ON
  -DNLOPT_INCLUDE_DIR:PATH=${NLOPT_SRC_DIR}
  -DNLOPT_LIBRARY_DIR:PATH=${NLOPT_BUILD_DIR}
  -DUSE_RPI:BOOL=ON
  -DUSE_VTK:BOOL=ON
  -DRPI_DIR:PATH=${RPI_BUILD_DIR}
  -DITK_DIR:PATH=${ITK_BUILD_DIR}
  -DVTK_DIR:PATH=${VTK_BUILD_DIR}
  -DBoost_INCLUDE_DIR:PATH=${Boost_SRC_DIR}
  -DTCLAP_INCLUDE_DIR:PATH=${TCLAP_SRC_DIR}/include
  )

ExternalProject_Add(${proj}
  DEPENDS ${${proj}_DEPS}
  PREFIX ${CMAKE_BINARY_DIR}/${proj}
  SOURCE_DIR ${CMAKE_SOURCE_DIR}/Projects/${proj}
  CMAKE_ARGS ${cmake_args}
  BUILD_IN_SOURCE 0
  BINARY_DIR ${CMAKE_BINARY_DIR}/${proj}
  UPDATE_COMMAND ""
  INSTALL_COMMAND ""
  )
