OPTION(BUILD_ALL_MODULES "Build all ANIMA modules" ON)

OPTION(BUILD_MODULE_MATHS "Build ANIMA math-tools module" ON)
OPTION(BUILD_MODULE_FILTERING "Build ANIMA filtering module" ON)
OPTION(BUILD_MODULE_DIFFUSION "Build ANIMA diffusion module" ON)
OPTION(BUILD_MODULE_REGISTRATION "Build ANIMA registration module" ON)
OPTION(BUILD_MODULE_QUANTITATIVE_MRI "Build ANIMA quantitative MRI module" ON)
OPTION(BUILD_MODULE_SEGMENTATION "Build ANIMA segmentation module" ON)

# Cascading cases to make sure the right modules are indeed turned on

if (BUILD_ALL_MODULES)
  set(BUILD_MODULE_DIFFUSION ON CACHE BOOL "Build ANIMA diffusion module" FORCE)
  set(BUILD_MODULE_REGISTRATION ON CACHE BOOL "Build ANIMA registration module" FORCE)
  set(BUILD_MODULE_QUANTITATIVE_MRI ON CACHE BOOL "Build ANIMA quantitative MRI module" FORCE)
  set(BUILD_MODULE_SEGMENTATION ON CACHE BOOL "Build ANIMA segmentation module" FORCE)
endif()

if (BUILD_MODULE_DIFFUSION OR BUILD_MODULE_REGISTRATION OR BUILD_MODULE_QUANTITATIVE_MRI OR BUILD_MODULE_SEGMENTATION)
  set(BUILD_MODULE_FILTERING ON CACHE BOOL "Build ANIMA filtering module" FORCE)
endif()

if (BUILD_MODULE_FILTERING)
  set(BUILD_MODULE_MATHS ON CACHE BOOL "Build ANIMA math-tools module" FORCE)
endif()

set (${PROJECT_NAME}_HEADER_PATHS "")

set(${PROJECT_NAME}_INCLUDE_DIRS 
  "${Boost_INCLUDE_DIR}"
  "${TCLAP_INCLUDE_DIR}"
  "${NLOPT_INCLUDE_DIR}"
  "${GMP_INCLUDE_DIR}"
  "${MPFR_INCLUDE_DIR}"
  "${FLINT_INCLUDE_DIR}"
  "${ARB_INCLUDE_DIR}"
  "${TinyXML2_INCLUDE_DIR}"
)

if (BUILD_MODULE_MATHS)
  list(APPEND ${PROJECT_NAME}_HEADER_PATHS ${${PROJECT_NAME}_SOURCE_DIR}/math-tools)
endif()

if (BUILD_MODULE_FILTERING)
  list(APPEND ${PROJECT_NAME}_HEADER_PATHS ${${PROJECT_NAME}_SOURCE_DIR}/filtering)
endif()

if (BUILD_MODULE_DIFFUSION)
  list(APPEND ${PROJECT_NAME}_HEADER_PATHS ${${PROJECT_NAME}_SOURCE_DIR}/diffusion)
endif()

if (BUILD_MODULE_REGISTRATION)
  list(APPEND ${PROJECT_NAME}_HEADER_PATHS ${${PROJECT_NAME}_SOURCE_DIR}/registration)
endif()

if (BUILD_MODULE_QUANTITATIVE_MRI)
  list(APPEND ${PROJECT_NAME}_HEADER_PATHS ${${PROJECT_NAME}_SOURCE_DIR}/quantitative-mri)
endif()

if (BUILD_MODULE_SEGMENTATION)
  list(APPEND ${PROJECT_NAME}_HEADER_PATHS ${${PROJECT_NAME}_SOURCE_DIR}/segmentation)
endif()

list_header_directories_to_include(${PROJECT_NAME} ${${PROJECT_NAME}_HEADER_PATHS})
include_directories(${${PROJECT_NAME}_INCLUDE_DIRS})
