# This defines useful cmake variables for ITK libs

set(ITKIO_LIBRARIES
  ITKIOImageBase
  ITKIOBMP
  ITKIOBioRad
  ITKIOBruker
  ITKIOGDCM
  ITKIOGIPL
  ITKIOGE
  ITKIOHDF5
  ITKIOJPEG
  ITKIOLSM
  ITKIOMeta
  ITKIOMINC
  ITKIONIFTI
  ITKIONRRD
  ITKIOPNG
  ${ITKIOMINC_LIBRARIES}
  ${ITKIOPhilipsREC_LIBRARIES}
  ITKIOStimulate
  ITKIOTIFF
  ITKIOVTK
  ITKIOMRC
)

set(ITK_TRANSFORM_LIBRARIES
  ITKIOTransformBase
  ITKIOTransformInsightLegacy
  ITKIOTransformHDF5
  ITKIOTransformMatlab
)
